export const BIZ = {
  name: 'Kda Design Sdn Bhd',
  short: 'Kda Design',
  phone: '+60 16-652 3330',
  tel: '+60166523330',
  wa: '60166523330',
  addr: ['A-33A-12, Level 33A', 'Suasana Sentral Loft', 'Jalan Stesen Sentral 5', '50470 Kuala Lumpur'],
  address: 'A-33A-12, Level 33A, Suasana Sentral Loft, Jalan Stesen Sentral 5, 50470 Kuala Lumpur',
  maps: 'https://www.google.com/maps/place/Kda+Design+Sdn+Bhd/@3.1313807,101.6841478,17z',
  directions: 'https://www.google.com/maps/dir/?api=1&destination=3.131381,101.684148',
  rating: '4.7',
  reviews: 3,
}

export const CREDITS = {
  hero: { by: 'Slleong', lic: 'CC0', url: 'https://commons.wikimedia.org/wiki/File:KL_Sentral_1.jpg' },
  view: { by: 'CEphoto, Uwe Aranas', lic: 'CC BY-SA 3.0', url: 'https://commons.wikimedia.org/wiki/File:Kuala_Lumpur_Malaysia_City-view-from-LeMeridien-Sentral-01.jpg' },
  osm: 'https://www.openstreetmap.org/?mlat=3.131381&mlon=101.684148#map=17/3.131381/101.684148',
}

const en = {
  meta: {
    title: 'Kda Design Sdn Bhd | Interior Designer, Suasana Sentral Loft, KL Sentral',
    desc: 'Kda Design Sdn Bhd, interior designer at Level 33A, Suasana Sentral Loft, Jalan Stesen Sentral 5, Kuala Lumpur. Rated 4.7 on Google. Call or WhatsApp +60 16-652 3330.',
  },
  langLabel: 'BM',
  langAria: 'BM · Tukar ke Bahasa Melayu',
  a11y: { skip: 'Skip to content', main: 'Main', mobile: 'Mobile menu', menuOpen: 'Open menu', menuClose: 'Close menu', bar: 'Quick contact', pin: 'Kda Design location' },
  nav: [['services', 'Services'], ['approach', 'How we work'], ['faq', 'FAQ'], ['contact', 'Contact']] as [string, string][],
  waCta: 'WhatsApp',
  call: 'Call',
  directions: 'Directions',
  hero: {
    eyebrow: 'Kda Design Sdn Bhd · Kuala Lumpur',
    h1a: 'Interior design studio',
    h1b: 'in KL Sentral.',
    sub: 'Our studio is on Level 33A of Suasana Sentral Loft. Send us your floor plan and a few photos of the space on WhatsApp, then come in and we’ll go through it together.',
    cta: 'WhatsApp us',
    reviewsWord: 'Google reviews',
    appt: 'Meetings by appointment',
    photo: 'KL Sentral seen from the Perdana Botanical Gardens',
    credit: 'Photo: Slleong / Wikimedia Commons, CC0',
  },
  services: {
    kicker: 'Services',
    title: 'Projects we take on',
    intro: 'Tell us about the space first. Once we’ve seen the floor plan and photos, we’ll confirm what’s involved, how long it takes and what it costs.',
    items: [
      ['Condominiums & apartments', 'Layout, built-in storage, lighting and finishes for high-rise units.'],
      ['Landed homes', 'A single room, one floor or the whole house.'],
      ['Offices & workspaces', 'Space planning and fit-out for offices and small studios.'],
      ['Furniture & built-ins', 'Wardrobes, kitchen cabinets, TV consoles and shelving, made to measure.'],
    ] as [string, string][],
    illus: 'Illustrative photos (Unsplash), not Kda Design projects',
    sofaAlt: 'Living room with a green sofa beside floor-to-ceiling windows and city towers',
    diningAlt: 'Dining room with pendant lights and a window onto the city',
  },
  approach: {
    kicker: 'How we work',
    title: 'How a project runs',
    steps: [
      ['First meeting', 'We look at your floor plan, photos, budget range and how you use each room.'],
      ['Layout & concept', 'Layout options and a direction for materials and colours, agreed before detailed drawing.'],
      ['Drawings & samples', 'Detailed drawings, finishes and material samples you can see in person.'],
      ['Build & furniture', 'Carpentry, built-ins and furniture made and installed to the drawings.'],
      ['Handover', 'A final walk-through together and any small fixes before you move in.'],
    ] as [string, string][],
    note: 'A typical sequence. Every project is scoped with you first.',
  },
  faq: {
    kicker: 'FAQ',
    title: 'Common questions',
    items: [
      ['Where is the studio?', 'Unit A-33A-12 on Level 33A of Suasana Sentral Loft, Jalan Stesen Sentral 5, 50470 Kuala Lumpur, in the KL Sentral area. On Google Maps it shows under the Suasana Sentral Loft P6 lobby.'],
      ['Do I need an appointment?', 'Yes, please message or call first. The studio is in a residential tower, so arranging a time makes sure someone is there to meet you.'],
      ['What should I bring to the first meeting?', 'A floor plan if you have one, photos or a short video of the space, a rough budget range and any pictures of rooms you like.'],
      ['Do you only do condos?', 'No. Landed homes, offices and furniture or built-in pieces are welcome too. Tell us about the space and we’ll let you know if it’s a fit.'],
      ['Can we talk in Bahasa Melayu?', 'Yes. Message us in English or Bahasa Melayu, whichever you prefer.'],
    ] as [string, string][],
  },
  contact: {
    kicker: 'Contact',
    title: 'Visit the studio',
    address: 'Address',
    phone: 'Phone & WhatsApp',
    hours: 'Opening hours',
    hoursText: 'By appointment only. Message or call to arrange a time.',
    getting: 'Getting here',
    gettingText: 'In the KL Sentral area, a short walk from KL Sentral station (LRT, MRT, KTM and KLIA Ekspres). Visitor parking depends on the building, so ask us when you book.',
    reviews: 'On Google',
    reviewsText: 'from 3 reviews',
    readReviews: 'See on Google Maps',
    maps: 'Open in Google Maps',
    mapAlt: 'Street map of the KL Sentral and Brickfields area with the studio marked',
    mapCredit: 'Map © OpenStreetMap contributors',
    view: 'Looking west from KL Sentral over the Lake Gardens',
    viewCredit: 'Photo: CEphoto, Uwe Aranas / Wikimedia Commons, CC BY-SA 3.0',
    waMsg: 'Hi Kda Design, I’d like to ask about an interior design project.',
  },
  footer: {
    explore: 'Explore',
    reach: 'Contact',
    hours: 'By appointment',
    photos: 'Photos: KL Sentral (Slleong, CC0) and the Lake Gardens view (CEphoto, Uwe Aranas, CC BY-SA 3.0) via Wikimedia Commons. Interior photos are illustrative stock images (Unsplash), not Kda Design projects.',
    pitch: 'Website concept prepared for this studio. Not an official site yet — open to making it yours.',
    pitchLink: 'Contact the designer',
    rights: 'All rights reserved.',
    toTop: 'Back to top',
  },
}

export type Content = typeof en

const ms: Content = {
  meta: {
    title: 'Kda Design Sdn Bhd | Pereka Dalaman, Suasana Sentral Loft, KL Sentral',
    desc: 'Kda Design Sdn Bhd, pereka dalaman di Aras 33A, Suasana Sentral Loft, Jalan Stesen Sentral 5, Kuala Lumpur. Penarafan 4.7 di Google. Telefon atau WhatsApp +60 16-652 3330.',
  },
  langLabel: 'EN',
  langAria: 'EN · Switch to English',
  a11y: { skip: 'Langkau ke kandungan', main: 'Utama', mobile: 'Menu mudah alih', menuOpen: 'Buka menu', menuClose: 'Tutup menu', bar: 'Hubungi pantas', pin: 'Lokasi Kda Design' },
  nav: [['services', 'Perkhidmatan'], ['approach', 'Cara kerja'], ['faq', 'Soalan lazim'], ['contact', 'Hubungi']],
  waCta: 'WhatsApp',
  call: 'Telefon',
  directions: 'Arah',
  hero: {
    eyebrow: 'Kda Design Sdn Bhd · Kuala Lumpur',
    h1a: 'Studio reka bentuk dalaman',
    h1b: 'di KL Sentral.',
    sub: 'Studio kami di Aras 33A, Suasana Sentral Loft. Hantar pelan lantai dan beberapa gambar ruang anda melalui WhatsApp, kemudian datang ke studio untuk berbincang.',
    cta: 'WhatsApp kami',
    reviewsWord: 'ulasan Google',
    appt: 'Pertemuan dengan temu janji',
    photo: 'KL Sentral dilihat dari Taman Botani Perdana',
    credit: 'Foto: Slleong / Wikimedia Commons, CC0',
  },
  services: {
    kicker: 'Perkhidmatan',
    title: 'Projek yang kami terima',
    intro: 'Ceritakan tentang ruang anda dahulu. Selepas melihat pelan lantai dan gambar, kami akan maklumkan skop kerja, tempoh dan kosnya.',
    items: [
      ['Kondominium & apartmen', 'Susun atur, storan terbina dalam, pencahayaan dan kemasan untuk unit bertingkat.'],
      ['Rumah bertanah', 'Satu bilik, satu tingkat atau seluruh rumah.'],
      ['Pejabat & ruang kerja', 'Perancangan ruang dan ubah suai untuk pejabat dan studio kecil.'],
      ['Perabot & kabinet', 'Almari pakaian, kabinet dapur, konsol TV dan rak, ditempah ikut ukuran.'],
    ],
    illus: 'Foto ilustrasi (Unsplash), bukan projek Kda Design',
    sofaAlt: 'Ruang tamu dengan sofa hijau di tepi tingkap kaca dan menara kota',
    diningAlt: 'Ruang makan dengan lampu gantung dan tingkap menghadap kota',
  },
  approach: {
    kicker: 'Cara kerja',
    title: 'Bagaimana projek berjalan',
    steps: [
      ['Pertemuan pertama', 'Kami teliti pelan lantai, gambar, anggaran bajet dan cara anda menggunakan setiap bilik.'],
      ['Susun atur & konsep', 'Pilihan susun atur serta hala tuju bahan dan warna, dipersetujui sebelum lukisan terperinci.'],
      ['Lukisan & sampel', 'Lukisan terperinci, kemasan dan sampel bahan yang boleh anda lihat sendiri.'],
      ['Binaan & perabot', 'Kerja kayu, kabinet terbina dalam dan perabot dibuat serta dipasang mengikut lukisan.'],
      ['Serahan', 'Pemeriksaan akhir bersama dan pembaikan kecil sebelum anda masuk.'],
    ],
    note: 'Urutan biasa. Skop setiap projek dibincang bersama anda dahulu.',
  },
  faq: {
    kicker: 'Soalan lazim',
    title: 'Soalan lazim',
    items: [
      ['Di mana studio anda?', 'Unit A-33A-12, Aras 33A, Suasana Sentral Loft, Jalan Stesen Sentral 5, 50470 Kuala Lumpur, di kawasan KL Sentral. Di Google Maps, ia tersenarai di bawah lobi P6 Suasana Sentral Loft.'],
      ['Perlukah buat temu janji?', 'Ya, sila mesej atau telefon dahulu. Studio berada di menara kediaman, jadi temu janji memastikan ada orang untuk menyambut anda.'],
      ['Apa yang perlu dibawa semasa pertemuan pertama?', 'Pelan lantai jika ada, gambar atau video pendek ruang, anggaran bajet dan gambar bilik yang anda suka.'],
      ['Kondo sahaja ke?', 'Tidak. Rumah bertanah, pejabat serta perabot atau kabinet terbina dalam pun boleh. Ceritakan tentang ruang anda dan kami akan maklumkan jika sesuai.'],
      ['Boleh berbincang dalam Bahasa Melayu?', 'Boleh. Mesej kami dalam Bahasa Melayu atau Bahasa Inggeris, mana-mana yang anda selesa.'],
    ],
  },
  contact: {
    kicker: 'Hubungi',
    title: 'Kunjungi studio',
    address: 'Alamat',
    phone: 'Telefon & WhatsApp',
    hours: 'Waktu operasi',
    hoursText: 'Dengan temu janji sahaja. Mesej atau telefon untuk tetapkan masa.',
    getting: 'Cara ke sini',
    gettingText: 'Di kawasan KL Sentral, berjalan kaki sebentar dari stesen KL Sentral (LRT, MRT, KTM dan KLIA Ekspres). Parkir pelawat bergantung pada bangunan, jadi tanya kami semasa membuat temu janji.',
    reviews: 'Di Google',
    reviewsText: 'daripada 3 ulasan',
    readReviews: 'Lihat di Google Maps',
    maps: 'Buka di Google Maps',
    mapAlt: 'Peta jalan kawasan KL Sentral dan Brickfields dengan lokasi studio ditanda',
    mapCredit: 'Peta © penyumbang OpenStreetMap',
    view: 'Pemandangan ke arah barat dari KL Sentral, merentasi Taman Tasik Perdana',
    viewCredit: 'Foto: CEphoto, Uwe Aranas / Wikimedia Commons, CC BY-SA 3.0',
    waMsg: 'Hai Kda Design, saya ingin bertanya tentang projek reka bentuk dalaman.',
  },
  footer: {
    explore: 'Laman',
    reach: 'Hubungi',
    hours: 'Dengan temu janji',
    photos: 'Foto: KL Sentral (Slleong, CC0) dan pemandangan Taman Tasik Perdana (CEphoto, Uwe Aranas, CC BY-SA 3.0) melalui Wikimedia Commons. Foto dalaman ialah imej stok ilustrasi (Unsplash), bukan projek Kda Design.',
    pitch: 'Konsep laman web disediakan untuk studio ini. Bukan laman rasmi lagi — sedia dijadikan milik anda.',
    pitchLink: 'Hubungi pereka',
    rights: 'Hak cipta terpelihara.',
    toTop: 'Kembali ke atas',
  },
}

export const content = { en, ms }
