export const BIZ = {
  name: 'Kda Design Sdn Bhd',
  short: 'Kda Design',
  phone: '+60 16-652 3330',
  tel: '+60166523330',
  wa: '60166523330',
  address: 'A-33A-12, Level 33A, Suasana Sentral Loft, Jalan Stesen Sentral 5, 50470 Kuala Lumpur',
  maps: 'https://www.google.com/maps/place/Kda+Design+Sdn+Bhd/@3.1313807,101.6841478,17z',
  directions: 'https://www.google.com/maps/dir/?api=1&destination=3.131381,101.684148',
  rating: '4.7',
  reviews: 3,
}

const en = {
  meta: {
    title: 'Kda Design Sdn Bhd | Interior Design Studio, Level 33A, KL Sentral, Kuala Lumpur',
    desc: 'Interior design from a studio on Level 33A of Suasana Sentral Loft, KL Sentral. Homes, condos, workspaces and furniture. Arrange a studio visit on WhatsApp.',
  },
  langLabel: 'BM',
  langAria: 'BM · Tukar ke Bahasa Melayu',
  a11y: { skip: 'Skip to content', main: 'Main', mobile: 'Mobile menu', menuOpen: 'Open menu', menuClose: 'Close menu', bar: 'Quick contact', prev: 'Previous image', next: 'Next image', gallery: 'Mood board, swipe for more' },
  nav: [['spaces', 'Spaces'], ['moodboard', 'Mood board'], ['process', 'Process'], ['visit', 'Visit'], ['studio', 'Studio']] as [string, string][],
  waCta: 'WhatsApp',
  hero: {
    eyebrow: 'Level 33A · KL Sentral',
    h1a: 'Interiors designed',
    h1b: 'with the city in view.',
    sub: 'An interior design studio on Level 33A, KL Sentral. Bring your floor plan and photos; we’ll shape the rooms around how you live and work.',
    cta: 'Plan a studio visit',
    cta2: 'WhatsApp the studio',
    reviewsWord: 'Google reviews',
    photo: 'Illustrative photo',
    plaque: 'Suasana Sentral Loft',
  },
  spaces: {
    kicker: 'Spaces',
    title: 'Bring us a floor plan.',
    note: 'Not sure your project fits? Send the plan and a few photos. We’ll tell you honestly.',
    items: [
      ['Condo & apartment', 'Compact layouts that work harder: storage, light and a view you actually face.'],
      ['Landed home', 'Room by room or the whole house, with one idea running through every space.'],
      ['Workspace', 'Offices and studios planned around how your team really works.'],
      ['Furniture & built-ins', 'Wardrobes, consoles, desks and shelving drawn for the room they live in.'],
    ] as [string, string][],
  },
  mood: {
    kicker: 'Mood board',
    title: 'Rooms that face the right way.',
    sub: 'The kind of spaces we like to draw. Illustrative stock images, not Kda projects.',
    items: [
      { img: 'dining', w: 507, h: 760, cap: 'Dining with a skyline', alt: 'Dark dining room with pendant lights and a window onto the city' },
      { img: 'lounge', w: 1056, h: 760, cap: 'Soft forms, warm timber', alt: 'Lounge with curved chairs, timber wall panels and artwork' },
      { img: 'nook', w: 608, h: 760, cap: 'A quiet corner', alt: 'Calm reading corner with stone shelves and a rounded armchair' },
      { img: 'calm', w: 1014, h: 760, cap: 'Layered neutrals', alt: 'Neutral living room with arched wall, round mirrors and pendant lamps' },
      { img: 'walnut', w: 1140, h: 760, cap: 'Built to fit', alt: 'Close-up of a walnut cabinet with a small plant on top' },
    ],
  },
  process: {
    kicker: 'Process',
    title: 'From brief to keys, in five steps.',
    steps: [
      ['Brief', 'Your floor plan, photos, budget range and how you use each room.'],
      ['Concept', 'Layout options and a mood direction, agreed before detailed drawing.'],
      ['Drawings & materials', 'Detailed drawings, finishes and samples you can see and touch.'],
      ['Build & furniture', 'The drawings become built-ins, furniture and finished rooms.'],
      ['Handover', 'A final walk-through together and the small fixes before you move in.'],
    ] as [string, string][],
    note: 'A typical sequence. Every project is scoped with you first.',
  },
  visit: {
    kicker: 'Visit',
    title: 'Come up to Level 33A.',
    sub: 'Pick a day and time. We’ll turn it into a WhatsApp message for the studio to confirm.',
    day: 'Preferred day',
    time: 'Time of day',
    times: ['Morning', 'Afternoon', 'Evening'],
    type: 'Your project',
    types: ['Condo / apartment', 'Landed home', 'Workspace', 'Furniture & built-ins'],
    bring: 'I’ll bring',
    brings: ['Floor plan', 'Photos of the space', 'Inspiration images'],
    preview: 'Your message',
    send: 'Send request on WhatsApp',
    hint: 'A request, not a booking. The studio will reply to confirm a time.',
    msgHi: 'Hi Kda Design, I’d like to arrange a visit to your studio at Suasana Sentral Loft.',
    msgDay: 'Preferred day',
    msgTime: 'Time',
    msgType: 'Project',
    msgBring: 'I’ll bring',
    msgEnd: 'Please let me know a time that works.',
    any: 'Any',
    days: 'Next 7 days, swipe for more',
    photo: 'Illustrative photo',
  },
  studio: {
    title: 'The studio',
    address: 'Address',
    phone: 'Phone & WhatsApp',
    getting: 'Getting here',
    gettingText: 'Suasana Sentral Loft, Jalan Stesen Sentral 5, KL Sentral. Google Maps lists the studio under the P6 lobby.',
    hours: 'Visits',
    hoursText: 'By appointment. Message to arrange a time.',
    maps: 'Open in Google Maps',
    directions: 'Get directions',
    call: 'Call',
    waMsg: 'Hi Kda Design, I’d like to ask about an interior design project.',
  },
  faq: {
    kicker: 'Questions',
    title: 'Before you visit.',
    items: [
      ['Where exactly is the studio?', 'A-33A-12 on Level 33A of Suasana Sentral Loft, Jalan Stesen Sentral 5, in the KL Sentral area. Google Maps lists it under the Suasana Sentral Loft P6 lobby.'],
      ['Do I need an appointment?', 'Please message first. The studio is in a residential tower, so arranging a time makes sure someone is there to meet you.'],
      ['What should I bring to the first meeting?', 'A floor plan if you have one, photos or a short video of the space, a rough budget range and any pictures of rooms you like.'],
      ['Do you work on condos only?', 'No. Condos, landed homes and workspaces are all welcome, as are furniture and built-in pieces. Tell us about the space and we’ll say if it’s a fit.'],
      ['Can we talk in Bahasa Melayu?', 'Yes. Message in English or Bahasa Melayu, whichever you prefer.'],
    ] as [string, string][],
  },
  footer: {
    tagline: 'Interior design · Level 33A, KL Sentral',
    photos: 'Photos are illustrative stock images (Unsplash), not Kda Design projects.',
    toTop: 'Back to top',
    pitch: 'Website concept prepared for this studio. Not an official site yet — open to making it yours.',
    pitchLink: 'Talk to the designer',
    rights: 'All trademarks belong to their owners.',
  },
}

export type Content = typeof en

const ms: Content = {
  meta: {
    title: 'Kda Design Sdn Bhd | Studio Reka Bentuk Dalaman, Aras 33A, KL Sentral, Kuala Lumpur',
    desc: 'Reka bentuk dalaman dari studio di Aras 33A, Suasana Sentral Loft, KL Sentral. Rumah, kondo, ruang kerja dan perabot. Atur lawatan studio melalui WhatsApp.',
  },
  langLabel: 'EN',
  langAria: 'EN · Switch to English',
  a11y: { skip: 'Langkau ke kandungan', main: 'Utama', mobile: 'Menu mudah alih', menuOpen: 'Buka menu', menuClose: 'Tutup menu', bar: 'Hubungi pantas', prev: 'Imej sebelumnya', next: 'Imej seterusnya', gallery: 'Papan suasana, leret untuk lagi' },
  nav: [['spaces', 'Ruang'], ['moodboard', 'Papan suasana'], ['process', 'Proses'], ['visit', 'Lawatan'], ['studio', 'Studio']],
  waCta: 'WhatsApp',
  hero: {
    eyebrow: 'Aras 33A · KL Sentral',
    h1a: 'Ruang dalaman direka',
    h1b: 'dengan kota di depan mata.',
    sub: 'Studio reka bentuk dalaman di Aras 33A, KL Sentral. Bawa pelan lantai dan gambar; kami bentukkan ruang mengikut cara anda tinggal dan bekerja.',
    cta: 'Rancang lawatan studio',
    cta2: 'WhatsApp studio',
    reviewsWord: 'ulasan Google',
    photo: 'Foto ilustrasi',
    plaque: 'Suasana Sentral Loft',
  },
  spaces: {
    kicker: 'Ruang',
    title: 'Bawa pelan lantai anda.',
    note: 'Tak pasti projek anda sesuai? Hantar pelan dan beberapa gambar. Kami akan beritahu dengan jujur.',
    items: [
      ['Kondo & apartmen', 'Susun atur kecil yang lebih berfungsi: storan, cahaya dan pemandangan yang benar-benar anda hadap.'],
      ['Rumah bertanah', 'Bilik demi bilik atau seluruh rumah, dengan satu idea dalam setiap ruang.'],
      ['Ruang kerja', 'Pejabat dan studio yang dirancang mengikut cara pasukan anda bekerja.'],
      ['Perabot & kabinet', 'Almari pakaian, konsol, meja dan rak yang dilukis untuk bilik ia ditempatkan.'],
    ],
  },
  mood: {
    kicker: 'Papan suasana',
    title: 'Bilik yang menghadap arah yang betul.',
    sub: 'Jenis ruang yang kami suka reka. Imej stok ilustrasi, bukan projek Kda.',
    items: [
      { img: 'dining', w: 507, h: 760, cap: 'Ruang makan dengan latar kota', alt: 'Ruang makan gelap dengan lampu gantung dan tingkap menghadap kota' },
      { img: 'lounge', w: 1056, h: 760, cap: 'Bentuk lembut, kayu hangat', alt: 'Ruang rehat dengan kerusi melengkung, panel kayu dan karya seni' },
      { img: 'nook', w: 608, h: 760, cap: 'Sudut yang tenang', alt: 'Sudut bacaan yang tenang dengan rak batu dan kerusi bulat' },
      { img: 'calm', w: 1014, h: 760, cap: 'Warna neutral berlapis', alt: 'Ruang tamu neutral dengan dinding melengkung, cermin bulat dan lampu gantung' },
      { img: 'walnut', w: 1140, h: 760, cap: 'Dibina mengikut ukuran', alt: 'Kabinet kayu walnut dengan pokok kecil di atasnya' },
    ],
  },
  process: {
    kicker: 'Proses',
    title: 'Dari taklimat hingga kunci, lima langkah.',
    steps: [
      ['Taklimat', 'Pelan lantai, gambar, anggaran bajet dan cara anda menggunakan setiap bilik.'],
      ['Konsep', 'Pilihan susun atur dan hala tuju suasana, dipersetujui sebelum lukisan terperinci.'],
      ['Lukisan & bahan', 'Lukisan terperinci, kemasan dan sampel yang boleh anda lihat dan sentuh.'],
      ['Binaan & perabot', 'Lukisan menjadi kabinet terbina dalam, perabot dan bilik yang siap.'],
      ['Serahan', 'Pemeriksaan akhir bersama dan pembetulan kecil sebelum anda masuk.'],
    ],
    note: 'Urutan biasa. Setiap projek diskopkan bersama anda dahulu.',
  },
  visit: {
    kicker: 'Lawatan',
    title: 'Naiklah ke Aras 33A.',
    sub: 'Pilih hari dan masa. Kami jadikannya mesej WhatsApp untuk studio sahkan.',
    day: 'Hari pilihan',
    time: 'Waktu',
    times: ['Pagi', 'Petang', 'Malam'],
    type: 'Projek anda',
    types: ['Kondo / apartmen', 'Rumah bertanah', 'Ruang kerja', 'Perabot & kabinet terbina dalam'],
    bring: 'Saya akan bawa',
    brings: ['Pelan lantai', 'Gambar ruang', 'Imej inspirasi'],
    preview: 'Mesej anda',
    send: 'Hantar permintaan melalui WhatsApp',
    hint: 'Ini permintaan, bukan tempahan. Studio akan membalas untuk mengesahkan masa.',
    msgHi: 'Hai Kda Design, saya ingin mengatur lawatan ke studio anda di Suasana Sentral Loft.',
    msgDay: 'Hari pilihan',
    msgTime: 'Waktu',
    msgType: 'Projek',
    msgBring: 'Saya akan bawa',
    msgEnd: 'Mohon maklumkan masa yang sesuai.',
    any: 'Mana-mana',
    days: '7 hari akan datang, leret untuk lagi',
    photo: 'Foto ilustrasi',
  },
  studio: {
    title: 'Studio',
    address: 'Alamat',
    phone: 'Telefon & WhatsApp',
    getting: 'Cara ke sini',
    gettingText: 'Suasana Sentral Loft, Jalan Stesen Sentral 5, KL Sentral. Google Maps menyenaraikan studio di bawah lobi P6.',
    hours: 'Lawatan',
    hoursText: 'Dengan temu janji. Hantar mesej untuk mengatur masa.',
    maps: 'Buka di Google Maps',
    directions: 'Dapatkan arah',
    call: 'Telefon',
    waMsg: 'Hai Kda Design, saya ingin bertanya tentang projek reka bentuk dalaman.',
  },
  faq: {
    kicker: 'Soalan',
    title: 'Sebelum anda datang.',
    items: [
      ['Di mana sebenarnya studio ini?', 'A-33A-12 di Aras 33A, Suasana Sentral Loft, Jalan Stesen Sentral 5, di kawasan KL Sentral. Google Maps menyenaraikannya di bawah lobi P6 Suasana Sentral Loft.'],
      ['Perlukah saya buat temu janji?', 'Sila hantar mesej dahulu. Studio berada di menara kediaman, jadi mengatur masa memastikan ada orang untuk menyambut anda.'],
      ['Apa yang perlu saya bawa ke pertemuan pertama?', 'Pelan lantai jika ada, gambar atau video ringkas ruang, anggaran bajet dan gambar bilik yang anda suka.'],
      ['Adakah anda hanya buat kondo?', 'Tidak. Kondo, rumah bertanah dan ruang kerja semuanya dialu-alukan, begitu juga perabot dan kabinet terbina dalam. Ceritakan tentang ruang anda dan kami akan beritahu jika ia sesuai.'],
      ['Boleh berbincang dalam Bahasa Melayu?', 'Boleh. Hantar mesej dalam Bahasa Inggeris atau Bahasa Melayu, mana-mana yang anda selesa.'],
    ],
  },
  footer: {
    tagline: 'Reka bentuk dalaman · Aras 33A, KL Sentral',
    photos: 'Foto ialah imej stok ilustrasi (Unsplash), bukan projek Kda Design.',
    toTop: 'Kembali ke atas',
    pitch: 'Konsep laman web disediakan untuk studio ini. Bukan laman rasmi lagi — sedia dijadikan milik anda.',
    pitchLink: 'Hubungi pereka',
    rights: 'Semua tanda dagangan milik pemiliknya.',
  },
}

export const content = { en, ms }
